### ISSUE TITLE
Bug with exempi 2.5.0

### ISSUE THREAD

**Issue by gullevek** [gullevek/reverse_geolocate#1]
OS: High sierra
Brew install exempi 2.5.0

python script crashes with

Traceback (most recent call last):
  File "~/bin/reverse_geolocate.py", line 1105, in <module>
    data_set[xmp_field] = xmp.get_property(xmp_fields[xmp_field], xmp_field)
  File "/usr/local/lib/python3.7/site-packages/libxmp/core.py", line 195, in get_property
    value, _ = _cexempi.get_property(self.xmpptr, schema_ns, prop_name)
  File "/usr/local/lib/python3.7/site-packages/libxmp/exempi.py", line 670, in get_property
    _value, ctypes.byref(prop_bits))
  File "/usr/local/lib/python3.7/site-packages/libxmp/exempi.py", line 1702, in check_error
    raise XMPError(msg)
libxmp.XMPError: Exempi function failure ("unknown error").

**Comment by gullevek** [comment]
Fails when called for

schema: http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/
name: Location

**Comment by gullevek** [comment]
If the string is not found it fails

**Comment by gullevek** [comment]
Fixed with Version 1.1.1
